version: 2
jobs:
  BuildApplication:
    working_directory: ~/repo
    docker:
      - image: 'circleci/node:8.10.0'
    steps:
      - checkout
      - restore_cache:
          key: 'v2-dependencies-{{ checksum "project/package.json" }}'
      - run:
          name: Install dependencies
          command: cd project && npm install
      - save_cache:
          key: 'v2-dependencies-{{ checksum "project/package.json" }}'
          paths:
              - node_modules
      - run:
          name: Lint code
          command: npm run lint
      - run:
          name: Test code
          command: npm test
workflows:
  version: 2
  BuildApplicationWorkflow:
    jobs:
      - BuildApplication:
          context: app-environment-variables
