version: 2
jobs:
  BuildApplication:
    working_directory: /home/circleci/project
    docker:
      - image: 'circleci/node:8.10.0'
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: cd project && npm install
      - save_cache:
          key: 'v2-dependencies-{{ .Environment.CIRCLE_SHA1 }}'
          paths:
              - node_modules
  LintCode:
    working_directory: /home/circleci/project
    docker:
      - image: 'circleci/node:8.10.0'
    steps:
      - checkout
      - restore_cache:
          key: 'v2-dependencies-{{ .Environment.CIRCLE_SHA1 }}'
      - run:
          name: Lint code
          command: cd project && npm run lint
  MochaTests:
    working_directory: /home/circleci/project
    docker:
      - image: 'circleci/node:8.10.0'
    steps:
      - checkout
      - restore_cache:
          key: 'v2-dependencies-{{ .Environment.CIRCLE_SHA1 }}'
      - run:
          name: Test code
          command: cd project && npm test
workflows:
  version: 2
  BuildApplication-LintCode-MochaTests:
    jobs:
      - BuildApplication
      - LintCode:
          requires: 
            - BuildApplication
      - MochaTests:
          requires: 
            - BuildApplication
          context: app-environment-variables
