version: 2
jobs:
    build:
        working_directory: ~/repo
        docker:
            -
                image: 'circleci/node:8.10'
        steps:
            - checkout
            -
                restore_cache:
                    keys:
                        - 'v1-dependencies-{{ checksum "package.json" }}'
                        - v1-dependencies-
            -
                run:
                    name: Install dependencies
                    command: npm install
            -
                save_cache:
                    paths:
                        - node_modules
                    key: 'v1-dependencies-{{ checksum "package.json" }}'
            -
                run:
                    name: Lint code
                    command: npm run lint
            -
                run:
                    name: Test code
                    command: npm test
