version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: 'circleci/node:8.10.0'
    steps:
      - checkout
      - restore_cache:
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: 'v1-dependencies-{{ checksum "package.json" }}'
          paths:
              - node_modules
  lint:
      - run:
          name: Lint code
          command: npm run lint
  test:
      - run:
          name: Test code
          command: npm test
workflows:
  version: 2
  my-workflow:
    jobs:
      - build
      - lint
      - test:
          context: app-environment-variables
