version: 2
jobs:
  BuildApplication:
    docker:
      - image: 'circleci/node:8.10.0'
    steps:
      - checkout
      - restore_cache:
          key: 'v2-dependencies-{{ checksum "package.json" }}'
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: 'v2-dependencies-{{ checksum "package.json" }}'
          paths:
              - ${CIRCLE_WORKING_DIRECTORY}/node_modules
  LintCode:
    docker:
      - image: 'circleci/node:8.10.0'
    steps:
      - checkout
      - restore_cache:
          key: 'v2-dependencies-{{ checksum "package.json" }}'
      - run:
          name: Lint code
          command: npm run lint
  MochaTests:
    docker:
      - image: 'circleci/node:8.10.0'
    steps:
      - checkout
      - restore_cache:
          key: 'v2-dependencies-{{ checksum "package.json" }}'
      - run:
          name: Test code
          command: npm test
workflows:
  version: 2
  BuildApplication-LintCode-MochaTests:
    jobs:
      - BuildApplication
      - LintCode:
          requires: 
            - BuildApplication
      - MochaTests:
          requires: 
            - BuildApplication
          context: app-environment-variables
